-- ============================================================
-- Migration 23 — Track who sent each check-in / location request
-- ============================================================
-- push_checks rows created by an admin/HR "Send" or "Send to all" click
-- had no record of which admin triggered them — only traceable (briefly)
-- via Vercel's short-lived request logs. Adds a permanent record.
-- NULL sent_by/sent_by_name means the request was auto-generated by the
-- random-check scheduler (runPushTick with send_random=1), not a person.
-- ============================================================

ALTER TABLE public.push_checks
  ADD COLUMN IF NOT EXISTS sent_by      uuid REFERENCES public.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS sent_by_name text;
